# Generated by Django 2.1.2 on 2018-12-01 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_post_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
