# Generated by Django 2.1.2 on 2018-12-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20181201_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='spam_score',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
