# Generated by Django 2.1.2 on 2018-12-18 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_post_spam_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='spam_score',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
