# Generated by Django 2.1.2 on 2018-12-19 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20181218_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='spam_class',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
        ),
    ]
