# Generated by Django 2.1.2 on 2018-12-19 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_post_spam_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='spam_class',
            field=models.CharField(default='n/a', max_length=200),
        ),
    ]
